In [5]:
import xml.etree.ElementTree

In [8]:
import seaborn

In [7]:
import newspaper

In [13]:
import numpy as np

data = np.array([[1,1],[1,2],[1,3]])

print(data.shape)
print(data.size)
print(data.ndim)
print(data.nbytes)
print(data.dtype)

(3, 2)
6
2
24
int32


In [20]:
import numpy as np

print(np.array([1, 2, 3], dtype=np.int))

print(np.array([1, 2, 3], dtype=np.float))

print(np.array([1, 2, 3], dtype=np.complex))

data= np.array([1, 2, 3], dtype=np.float)
print(data.astype(np.int))

print(np.sqrt(-1, dtype=complex))

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]
1j


<ipython-input-20-74271bc43670>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.array([1, 2, 3], dtype=np.int))
<ipython-input-20-74271bc43670>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.array([1, 

In [22]:
import numpy as np

print(np.zeros((2,3)))

print(np.ones(4))
print(np.full(3,3.2))

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[3.2 3.2 3.2]


In [27]:
import numpy as np

a = np.arange(0, 11)

#a[0]
#a[-1]
a[4]
a[0:5]
#a[0:5:2]
#a[:5]
#a[-5:]
#a[::-2]

array([0, 1, 2, 3, 4])

In [29]:
a = np.array([[1,2,3,4],
[11,12,13,14],[21,22,23,24]
,[31,32,33,34]])

a[:,1]

array([ 2, 12, 22, 32])

In [31]:
A = np.linspace(0, 1, 11)

A[np.array([0, 2, 4])]
A[A>0.5]
#A[np.arange(2,5)]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [32]:
a = np.arange(3)
b = np.arange(4)

np.concatenate((a,b))

np.append(a,[3,4,5])

np.resize(b,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [46]:
import numpy as np
#np.cos(np.pi)
#np.sin(np.pi)
print(int(np.tan(np.pi)))
print(np.tan(np.pi))
print(np.sqrt(4))

print(np.log2(8))
print(np.log10(100))

0
-1.2246467991473532e-16
2.0
3.0
2.0


In [49]:
mat = np.arange(9).reshape(3, 3)

print(np.transpose(mat))
np.fliplr(mat)
np.flipud(mat)
print(np.rot90(mat))

c = [[2,3,1],[9,8,7]]
print(np.sort(c))

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[2 5 8]
 [1 4 7]
 [0 3 6]]
[[1 2 3]
 [7 8 9]]


In [58]:
import sympy
x = sympy.Symbol("x")
y = sympy.Symbol("y")

expr = 2 * (x**2 - x) - x * (x+1)
expr = 2 * sympy.cos(x) * sympy.sin(x)
expr3 = sympy.exp(x) * sympy.exp(y)
expr = 1 / (x**2 -1) + 1 / (x+1)

print(expr3)
print(sympy.simplify(expr3))

exp(x)*exp(y)
exp(x + y)


In [65]:
a, b, c, d = sympy.symbols("a, b, c, d")
M = sympy.Matrix([[a, b], [c, d]])

print(M * M)

x = sympy.Matrix(sympy.symbols("x_1, x_2"))
q = sympy.Matrix(sympy.symbols("q_1,q_2"))

x = M.inv()*q
print(sympy.solve(M*x - q,x))

Matrix([[a**2 + b*c, a*b + b*d], [a*c + c*d, b*c + d**2]])
{-b*q_2/(a*d - b*c) + d*q_1/(a*d - b*c): (-b*q_2 + d*q_1)/(a*d - b*c), a*q_2/(a*d - b*c) - c*q_1/(a*d - b*c): (a*q_2 - c*q_1)/(a*d - b*c)}
